version: "3.8"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/var/www/html/
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root # EDIT
      MYSQL_PASSWORD: secret # EDIT
      MYSQL_DB: zwa-project
  mysql:
    image: mysql:5.7
    environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: zwa-project
    ports:
      - 4000:3306
